#! /bin/sh

bspc rule -r "*"

compton --config $HOME/.config/compton.conf &
sxhkd &

xsetroot -cursor_name left_ptr &

nitrogen --set-scaled ~/Pictures/wallpaper/black-3840x2160.png

$HOME/.config/polybar/launch.sh

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

bspc config initial_polarity second_child

bspc config border_width          6
bspc config normal_border_color   "#1E1E1E"
bspc config focused_border_color  "#37447D"
bspc config active_border_color   "#1E1E1E"
bspc config presel_feedback_color "#1E1E1E"


bspc config window_gap           8

bspc config top_padding          0
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config click_to_focus       true

bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true
