#! /bin/sh

## DEFAUL SINK
#set-default-sink alsa_output.usb-Generic_USB_Audio-00.analog-stereo
#
#
## DEFAULT SOURCE
#set-default-source alsa_input.usb-Audient_EVO4-00.multichannel-input

bspc rule -r "*"

compton --config $HOME/.config/compton.conf &
numlockx &
sxhkd &
xsetroot -cursor_name left_ptr &
xinput --set-prop 12 'libinput Accel Speed' 1.0 &
nitrogen --set-scaled ~/Pictures/wallpaper/black-3840x2160.png

xmodmap ~/.xmodmaprc

pacmd 'load-module module-remap-source source_name="EVO4_REAR_LEFT" source_properties="device.description=evo-rear-left" master="alsa_input.usb-Audient_EVO4-00.multichannel-input" master_channel_map=front-left channel_map=aux0 remix=no'
pacmd 'load-module module-remap-source source_name="EVO4_REAR_RIGHT" source_properties="device.description=evo-rear-right" master="alsa_input.usb-Audient_EVO4-00.multichannel-input" master_channel_map=front-right channel_map=aux1 remix=no'
pacmd 'load-module module-remap-source source_name="EVO4_FRONT_LEFT" source_properties="device.description=evo-front-left" master="alsa_input.usb-Audient_EVO4-00.multichannel-input" master_channel_map=rear-left channel_map=aux2 remix=no'
pacmd 'load-module module-remap-source source_name="EVO4_FRONT_RIGHT" source_properties="device.description=evo-front-right" master="alsa_input.usb-Audient_EVO4-00.multichannel-input" master_channel_map=rear-right channel_map=aux3 remix=no'

pacmd 'set-default-sink alsa_output.usb-Generic_USB_Audio-00.analog-stereo'
#pacmd 'set-default-source alsa_input.usb-Audient_EVO4-00.multichannel-input'
pacmd 'set-default-source EVO4_REAR_LEFT'

$HOME/.config/polybar/launch.sh


bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

bspc config initial_polarity second_child

bspc config border_width          6
bspc config normal_border_color   "#1E1E1E"
bspc config focused_border_color  "#37447D"
bspc config active_border_color   "#1E1E1E"
bspc config presel_feedback_color "#1E1E1E"


bspc config window_gap           8

bspc config top_padding          0
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config click_to_focus       true

bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
